In [1824]:
# Import libraries
import pandas as pd
import numpy as np

In [1825]:
#Load dataset
df = pd.read_csv("Netflix_raw_data.csv")

In [1826]:
#View first 5 rows
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [1827]:
## Check rows and columns
df.shape

(8807, 12)

In [1828]:
# View column names
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [1829]:
# Check data types and null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [1830]:
# Count unique values in each column
for i in df.columns:
  print(i,':',df[i].nunique())

show_id : 8807
type : 2
title : 8804
director : 4528
cast : 7692
country : 748
date_added : 1767
release_year : 74
rating : 17
duration : 220
listed_in : 514
description : 8775

In [1831]:
# Check for missing values
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [1832]:
# Check for duplicate rows
df[df.duplicated()]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [1833]:
# Check if there are any duplicate rows
df.duplicated().any()

False

In [1834]:
# Create a copy of the dataframe
df1=df.copy()

In [1835]:
# Filter and sort duplicates based on selected columns
temp_df=df[df.duplicated(subset=['director', 'type', 'cast', 'country', 'date_added',
                         'release_year', 'rating', 'duration', 'listed_in'],keep=False)]\
  .sort_values(by='director')

In [1836]:
# Display the filtered and sorted duplicates
temp_df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
3570,s3571,Movie,Game Over (Telugu Version),Ashwin Saravanan,"Taapsee Pannu, Vinodhini, Parvathi T, Ramya Su...",NaN,"August 21, 2019",2019,TV-MA,98 min,"Horror Movies, International Movies, Thrillers","As a series of murders hit close to home, a vi..."
3568,s3569,Movie,Game Over (Hindi Version),Ashwin Saravanan,"Taapsee Pannu, Vinodhini, Parvathi T, Ramya Su...",NaN,"August 21, 2019",2019,TV-MA,98 min,"Horror Movies, International Movies, Thrillers","As a series of murders hit close to home, a vi..."
3492,s3493,Movie,Oh! Baby (Malayalam),B. V. Nandini Reddy,"Samantha Ruth Prabhu, Lakshmi, Rajendraprasad,...",NaN,"September 25, 2019",2019,TV-14,146 min,"Comedies, International Movies, Music & Musicals",A surly septuagenarian gets another chance at ...
3493,s3494,Movie,Oh! Baby (Tamil),B. V. Nandini Reddy,"Samantha Ruth Prabhu, Lakshmi, Rajendraprasad,...",NaN,"September 25, 2019",2019,TV-14,146 min,"Comedies, International Movies, Music & Musicals",A surly septuagenarian gets another chance at ...
5466,s5467,Movie,The Mitfords: A Tale of Two Sisters,Edward Cotterill,Rachael Stirling,United Kingdom,"June 1, 2017",2017,TV-PG,44 min,Documentaries,Jessica and Diana were sisters who were separa...
5451,s5452,Movie,Jackie: A Tale of Two Sisters,Edward Cotterill,Rachael Stirling,United Kingdom,"June 1, 2017",2017,TV-PG,44 min,Documentaries,Rachael Stirling narrates this multifaceted po...
5448,s5449,Movie,Amelia: A Tale of Two Sisters,Edward Cotterill,Rachael Stirling,United Kingdom,"June 1, 2017",2017,TV-PG,44 min,Documentaries,"Eight decades after her disappearance, Amelia ..."
760,s761,Movie,Fireplace 4K: Crackling Birchwood from Firepla...,George Ford,NaN,NaN,"June 4, 2021",2015,TV-G,60 min,Movies,"For the first time in 4K Ultra-HD, everyone's ..."
759,s760,Movie,Fireplace 4K: Classic Crackling Fireplace from...,George Ford,NaN,NaN,"June 4, 2021",2015,TV-G,60 min,Movies,"The first of its kind in UHD 4K, with the clea..."
6529,s6530,Movie,Consequences,Ozan Açıktan,"Nehir Erdoğan, Tardu Flordun, İlker Kaleli, Se...",Turkey,"October 25, 2019",2014,TV-MA,106 min,"Dramas, International Movies, Thrillers",Secrets bubble to the surface after a sensual ...
3371,s3372,Movie,Consequences,Ozan Açıktan,"Nehir Erdoğan, Tardu Flordun, İlker Kaleli, Se...",Turkey,"October 25, 2019",2014,TV-MA,106 min,"Dramas, International Movies, Thrillers",Secrets bubble to the surface after a sensual ...
4522,s4523,Movie,22-Jul,Paul Greengrass,"Anders Danielsen Lie, Jon Øigarden, Jonas Stra...","Norway, Iceland, United States","October 10, 2018",2018,R,144 min,"Dramas, Thrillers","After devastating terror attacks in Norway, a ..."
5965,s5966,Movie,22-Jul,Paul Greengrass,"Anders Danielsen Lie, Jon Øigarden, Jonas Stra...","Norway, Iceland, United States","October 10, 2018",2018,R,144 min,"Dramas, Thrillers","After devastating terror attacks in Norway, a ..."
414,s415,Movie,Chhota Bheem Aur Hanuman,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2012,TV-Y7,68 min,Children & Family Movies,When two evil entities kidnap a princess in a ...
413,s414,Movie,Chhota Bheem and The ShiNobi Secret,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2013,TV-Y7,64 min,Children & Family Movies,After learning of a samurai village under thre...
411,s412,Movie,Chhota Bheem And The Crown of Valhalla,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2013,TV-Y7,64 min,Children & Family Movies,To save the kingdom of Valhalla from invasion ...
406,s407,Movie,Chhota Bheem - Neeli Pahaadi,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2013,TV-Y7,64 min,Children & Family Movies,Things get spooky when Bheem and his buddies t...
416,s417,Movie,Chhota Bheem aur Krishna vs Zimbara,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2013,TV-Y7,64 min,Children & Family Movies,A demon of darkness is plotting world dominati...
424,s425,Movie,Chhota Bheem: The Rise of Kirmada,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2012,TV-Y7,68 min,Children & Family Movies,Bheem and young lord Krishna team up to protec...
236,s237,Movie,Boomika,Rathindran R Prasad,"Aishwarya Rajesh, Vidhu, Surya Ganapathy, Madh...",NaN,"August 23, 2021",2021,TV-14,122 min,"Horror Movies, International Movies, Thrillers","Paranormal activity at a lush, abandoned prope..."
239,s240,Movie,Boomika (Telugu),Rathindran R Prasad,"Aishwarya Rajesh, Vidhu, Surya Ganapathy, Madh...",NaN,"August 23, 2021",2021,TV-14,122 min,"Horror Movies, International Movies, Thrillers","Paranormal activity at a lush, abandoned prope..."
238,s239,Movie,Boomika (Malayalam),Rathindran R Prasad,"Aishwarya Rajesh, Vidhu, Surya Ganapathy, Madh...",NaN,"August 23, 2021",2021,TV-14,122 min,"Horror Movies, International Movies, Thrillers","Paranormal activity at a lush, abandoned prope..."
237,s238,Movie,Boomika (Hindi),Rathindran R Prasad,"Aishwarya Rajesh, Vidhu, Surya Ganapathy, Madh...",NaN,"August 23, 2021",2021,TV-14,122 min,"Horror Movies, International Movies, Thrillers","Paranormal activity at a lush, abandoned prope..."
8051,s8052,Movie,Solo: A Star Wars Story,Ron Howard,"Alden Ehrenreich, Woody Harrelson, Emilia Clar...",United States,"January 9, 2019",2018,PG-13,135 min,"Action & Adventure, Children & Family Movies, ...",A young Han Solo tries to settle an old score ...
8052,s8053,Movie,Solo: A Star Wars Story (Spanish Version),Ron Howard,"Alden Ehrenreich, Woody Harrelson, Emilia Clar...",United States,"January 9, 2019",2018,PG-13,135 min,"Action & Adventure, Children & Family Movies, ...",A young Han Solo tries to settle an old score ...
5966,s5967,Movie,15-Aug,Swapnaneel Jayakar,"Rahul Pethe, Mrunmayee Deshpande, Adinath Koth...",India,"March 29, 2019",2019,TV-14,124 min,"Comedies, Dramas, Independent Movies","On India's Independence Day, a zany mishap in ..."
3962,s3963,Movie,15-Aug,Swapnaneel Jayakar,"Rahul Pethe, Mrunmayee Deshpande, Adinath Koth...",India,"March 29, 2019",2019,TV-14,124 min,"Comedies, Dramas, Independent Movies","On India's Independence Day, a zany mishap in ..."
851,s852,Movie,99 Songs (Tamil),NaN,NaN,NaN,"May 21, 2021",2021,TV-14,131 min,"Dramas, International Movies, Music & Musicals",Challenged to compose 100 songs before he can ...
852,s853,Movie,99 Songs (Telugu),NaN,NaN,NaN,"May 21, 2021",2021,TV-14,131 min,"Dramas, International Movies, Music & Musicals",Challenged to compose 100 songs before he can ...
3996,s3997,TV Show,Feb-09,NaN,"Shahd El Yaseen, Shaila Sabt, Hala, Hanadi Al-...",NaN,"March 20, 2019",2018,TV-14,1 Season,"International TV Shows, TV Dramas","As a psychology professor faces Alzheimer's, h..."
4831,s4832,TV Show,True: Magical Friends,NaN,"Michela Luci, Jamie Watson, Anna Claire Bartla...",NaN,"June 15, 2018",2018,TV-Y,1 Season,Kids' TV,The power of friendship can solve any problem ...
4832,s4833,TV Show,True: Wonderful Wishes,NaN,"Michela Luci, Jamie Watson, Anna Claire Bartla...",NaN,"June 15, 2018",2018,TV-Y,1 Season,Kids' TV,Do-gooding True and Bartleby will go anywhere ...
5964,s5965,TV Show,Feb-09,NaN,"Shahd El Yaseen, Shaila Sabt, Hala, Hanadi Al-...",NaN,"March 20, 2019",2018,TV-14,1 Season,"International TV Shows, TV Dramas","As a psychology professor faces Alzheimer's, h..."
6785,s6786,TV Show,Forces of Nature,NaN,NaN,United Kingdom,"March 1, 2017",2016,TV-PG,1 Season,"British TV Shows, Docuseries, Science & Nature TV",This dynamic series spans the globe to explain...
8129,s8130,TV Show,SuperNature: Wild Flyers,NaN,NaN,United Kingdom,"March 1, 2017",2016,TV-PG,1 Season,"British TV Shows, Docuseries, Science & Nature TV",This series examines the aerodynamics of fligh...

In [1837]:
# Observed rows with similar-looking titles (e.g., different language versions of the same movie) 
# and confirmed they are not duplicates based on unique content in other columns. 
# Dropped the rows to clean the data without affecting unique entries. 
temp_df.drop([3570,3568,3492,3493,5466,5451,5448,760,759,414,413,411,406,416,424,236,237,238,239,8051,8052,851,852,4831,4832,6785,8129], axis=0,inplace=True)

In [1838]:
# Display the updated dataframe after dropping rows
temp_df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6529,s6530,Movie,Consequences,Ozan Açıktan,"Nehir Erdoğan, Tardu Flordun, İlker Kaleli, Se...",Turkey,"October 25, 2019",2014,TV-MA,106 min,"Dramas, International Movies, Thrillers",Secrets bubble to the surface after a sensual ...
3371,s3372,Movie,Consequences,Ozan Açıktan,"Nehir Erdoğan, Tardu Flordun, İlker Kaleli, Se...",Turkey,"October 25, 2019",2014,TV-MA,106 min,"Dramas, International Movies, Thrillers",Secrets bubble to the surface after a sensual ...
4522,s4523,Movie,22-Jul,Paul Greengrass,"Anders Danielsen Lie, Jon Øigarden, Jonas Stra...","Norway, Iceland, United States","October 10, 2018",2018,R,144 min,"Dramas, Thrillers","After devastating terror attacks in Norway, a ..."
5965,s5966,Movie,22-Jul,Paul Greengrass,"Anders Danielsen Lie, Jon Øigarden, Jonas Stra...","Norway, Iceland, United States","October 10, 2018",2018,R,144 min,"Dramas, Thrillers","After devastating terror attacks in Norway, a ..."
5966,s5967,Movie,15-Aug,Swapnaneel Jayakar,"Rahul Pethe, Mrunmayee Deshpande, Adinath Koth...",India,"March 29, 2019",2019,TV-14,124 min,"Comedies, Dramas, Independent Movies","On India's Independence Day, a zany mishap in ..."
3962,s3963,Movie,15-Aug,Swapnaneel Jayakar,"Rahul Pethe, Mrunmayee Deshpande, Adinath Koth...",India,"March 29, 2019",2019,TV-14,124 min,"Comedies, Dramas, Independent Movies","On India's Independence Day, a zany mishap in ..."
3996,s3997,TV Show,Feb-09,NaN,"Shahd El Yaseen, Shaila Sabt, Hala, Hanadi Al-...",NaN,"March 20, 2019",2018,TV-14,1 Season,"International TV Shows, TV Dramas","As a psychology professor faces Alzheimer's, h..."
5964,s5965,TV Show,Feb-09,NaN,"Shahd El Yaseen, Shaila Sabt, Hala, Hanadi Al-...",NaN,"March 20, 2019",2018,TV-14,1 Season,"International TV Shows, TV Dramas","As a psychology professor faces Alzheimer's, h..."

In [1839]:
# Observed duplicate entries with identical data (same movie/show with slight variations in title coloumn) 
# Drop additional specific rows by index
temp_df.drop([6529,4522,5966,3996],axis=0, inplace=True)

In [1840]:
# Dropped the rows identified as duplicates from the original dataframe (df) based on the indices from temp_df.
df = df.drop(temp_df.index)

In [1841]:
# Checking the shape of the dataframe after dropping the duplicate rows
df.shape

(8803, 12)

In [1842]:
#Checking the distribution of values in the 'type' column (e.g., 'Movie', 'TV Show')
df['type'].value_counts()

type
Movie      6128
TV Show    2675
Name: count, dtype: int64

In [1843]:
# Checking the distribution of values in the 'director' column to see the frequency of directors
df['director'].value_counts()

director
Rajiv Chilaka             19
Raúl Campos, Jan Suter    18
Marcus Raboy              16
Suhas Kadav               16
Jay Karas                 14
                          ..
Joe Menendez               1
Eric Bross                 1
Will Eisenberg             1
Marina Seresesky           1
Mozez Singh                1
Name: count, Length: 4528, dtype: int64

In [1844]:
# for col in df.columns:
#     print(f"{'='*40} {col} {'='*40}")
#     print(df[col].value_counts(dropna=False))
#     print("\n")

In [1845]:
# Checking the distribution of values in the 'cast' column to see the frequency of actors/actresses
df['cast'].value_counts()

cast
David Attenborough                                                                                                                                                                            19
Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jigna Bhardwaj, Rajesh Kava, Mousam, Swapnil                                                                                                       14
Samuel West                                                                                                                                                                                   10
Jeff Dunham                                                                                                                                                                                    7
Kevin Hart                                                                                                                                                                                     6
                                                                                                                                                                                              ..
Michael Peña, Diego Luna, Tenoch Huerta, Joaquin Cosio, José María Yazpik, Matt Letscher, Alyssa Diaz                                                                                          1
Nick Lachey, Vanessa Lachey                                                                                                                                                                    1
Takeru Sato, Kasumi Arimura, Haru, Kentaro Sakaguchi, Takayuki Yamada, Kendo Kobayashi, Ken Yasuda, Arata Furuta, Suzuki Matsuo, Koichi Yamadera, Arata Iura, Chikako Kaku, Kotaro Yoshida     1
Toyin Abraham, Sambasa Nzeribe, Chioma Chukwuka Akpotha, Chioma Omeruah, Chiwetalu Agu, Dele Odule, Femi Adebayo, Bayray McNwizu, Biodun Stephen                                               1
Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanana, Manish Chaudhary, Meghna Malik, Malkeet Rauni, Anita Shabdish, Chittaranjan Tripathy                                                          1
Name: count, Length: 7692, dtype: int64

In [1846]:
# Checking the distribution of values in the 'date_added' column to see how many titles were added on each date
df['date_added'].value_counts()

date_added
January 1, 2020      109
November 1, 2019      89
March 1, 2018         75
December 31, 2019     74
October 1, 2018       71
                    ...
December 4, 2016       1
November 21, 2016      1
November 19, 2016      1
November 17, 2016      1
January 11, 2020       1
Name: count, Length: 1767, dtype: int64

In [1847]:
# Checking the distribution of values in the 'release_year' column to see how many titles were released in each year
df['release_year'].value_counts()

release_year
2018    1145
2017    1032
2019    1029
2020     953
2016     902
        ...
1959       1
1925       1
1961       1
1947       1
1966       1
Name: count, Length: 74, dtype: int64

In [1848]:
# Checking the distribution of values in the 'listed_in' column to see how many titles belong to each category
df['listed_in'].value_counts()

listed_in
Dramas, International Movies                          362
Documentaries                                         359
Stand-Up Comedy                                       334
Comedies, Dramas, International Movies                274
Dramas, Independent Movies, International Movies      252
                                                     ...
Kids' TV, TV Action & Adventure, TV Dramas              1
TV Comedies, TV Dramas, TV Horror                       1
Children & Family Movies, Comedies, LGBTQ Movies        1
Kids' TV, Spanish-Language TV Shows, Teen TV Shows      1
Cult Movies, Dramas, Thrillers                          1
Name: count, Length: 514, dtype: int64

In [1849]:
# Checking the distribution of values in the 'rating' column to see how many titles fall under each rating category
df['rating'].value_counts()

rating
TV-MA       3206
TV-14       2158
TV-PG        863
R            798
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NC-17          3
UR             3
74 min         1
84 min         1
66 min         1
Name: count, dtype: int64

In [1850]:
# Checking the distribution of values in the 'duration' column to see how many titles fall under each duration category
df['duration'].value_counts()

duration
1 Season     1792
2 Seasons     425
3 Seasons     199
90 min        152
94 min        146
             ...
16 min          1
186 min         1
193 min         1
189 min         1
191 min         1
Name: count, Length: 220, dtype: int64

In [1851]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [1852]:
def unstack_col(df, col):
    """
    This function unpacks a comma-separated column (e.g., director, cast, country, listed_in) into individual rows.
    Each value in the column is split and expanded into separate rows, while the 'title' remains as the index.

    Parameters:
    df (DataFrame): The input DataFrame containing the column to unstack.
    col (str): The name of the column to unstack (e.g., 'director', 'cast', etc.).

    Returns:
    DataFrame: A new DataFrame with unstacked values in the specified column.
    """
    Constraint = df[col].apply(lambda x: str(x).split(", ")).tolist()
    df_new1 = pd.DataFrame(Constraint, index=df['title']).stack().reset_index()
    df_new1.drop("level_1", axis=1, inplace=True)
    df_new1.rename({0: col}, axis=1, inplace=True)
    return df_new1

In [1853]:
# #unnesting the directors column, i.e- creating separate lines for each director in a movie
# constraint1 = df['director'].apply(lambda x: str(x).split(', ')).tolist()
# df_new1=pd.DataFrame(constraint1,index=df['title'])
# df_new1=df_new1.stack()
# df_new1=pd.DataFrame(df_new1.reset_index())
# df_new1.rename(columns={0:'Directors'},inplace=True)
# df_new1.drop(['level_1'],axis=1,inplace=True)
# df_new1.head()

In [1854]:
# Unnesting the 'director' column, i.e., creating separate rows for each director in a movie
temp_df1=unstack_col(df,'director')

In [1855]:
# Unnesting the 'cast' column, i.e., creating separate rows for each cast member in a movie
temp_df2=unstack_col(df,'cast')

In [1856]:
#unnesting the country column, i.e., creating separate lines for each country in a movie
temp_df3=unstack_col(df,'country')

In [1857]:
# Unnesting the 'country' column, i.e., creating separate rows for each country in a movie
temp_df4=unstack_col(df,'listed_in')

In [1858]:
# Comparing the shapes of the dataframes (temp_df1, temp_df2, temp_df3, temp_df4) before merging
print(temp_df1.shape, temp_df2.shape, temp_df3.shape, temp_df4.shape)

(9608, 2) (64918, 2) (10839, 2) (19313, 2)

In [1859]:
# Merging dataframes step by step, each time adding a new column (director, cast, country)
df_temp = temp_df2.merge(temp_df1, on='title', how='inner')  # Merging cast and director information
df_temp = df_temp.merge(temp_df3, on='title', how='inner')   # Adding genre information
df_new  = df_temp.merge(temp_df4, on='title', how='inner')   # Adding country information

In [1860]:
#compare shapes after merging
print(temp_df1.shape, temp_df2.shape, temp_df3.shape, temp_df4.shape)

(9608, 2) (64918, 2) (10839, 2) (19313, 2)

In [1861]:
df_new.shape

(201881, 5)

In [1862]:
# Replacing missing string values in the cast and director columns with 'Unknown Actor' and 'Unknown Director' to maintain consistency in categorical analysis.
# For the country column, keeping missing values as NaN allows proper handling in statistical or geographical analysis.
df_new['cast'] = df_new['cast'].replace('nan', 'Unknown Actor')
df_new['director'] = df_new['director'].replace('nan', 'Unknown Director')
df_new['country'] = df_new['country'].replace('nan', np.nan)

In [1863]:
#merging our unnested data with the original data
df_final=df_new.merge(df[['show_id', 'type', 'title', 'date_added',
       'release_year', 'rating', 'duration']],on=['title'],how='left')
df_final.head()

,title,cast,director,country,listed_in,show_id,type,date_added,release_year,rating,duration
0,Dick Johnson Is Dead,Unknown Actor,Kirsten Johnson,United States,Documentaries,s1,Movie,"September 25, 2021",2020,PG-13,90 min
1,Blood & Water,Ama Qamata,Unknown Director,South Africa,International TV Shows,s2,TV Show,"September 24, 2021",2021,TV-MA,2 Seasons
2,Blood & Water,Ama Qamata,Unknown Director,South Africa,TV Dramas,s2,TV Show,"September 24, 2021",2021,TV-MA,2 Seasons
3,Blood & Water,Ama Qamata,Unknown Director,South Africa,TV Mysteries,s2,TV Show,"September 24, 2021",2021,TV-MA,2 Seasons
4,Blood & Water,Khosi Ngema,Unknown Director,South Africa,International TV Shows,s2,TV Show,"September 24, 2021",2021,TV-MA,2 Seasons

In [1864]:
# Rearranging columns for better readability and consistent structure
df_final = df_final[['show_id', 'type', 'title', 'director', 'cast', 'country',
                     'date_added', 'release_year', 'rating', 'duration',
                     'listed_in']]

In [1865]:
# Viewing final dataset dimensions
df_final.shape

(201881, 11)

In [1866]:
# Count of duplicate rows
print("Duplicate rows:", df_final.duplicated().sum())

Duplicate rows: 55

In [1867]:
#extracting all the duplicate rows from the df_final DataFrame and storing them in the duplicated_data DataFrame. 
#This allows you to keep a record of all the duplicate rows for future analysis or reference.
duplicated_data=df_final[df_final.duplicated()]

In [1868]:
duplicated_data  
# Here i observed that there are real duplicate rows, such as for the title 'Blood Will Tell,' where the director's name creates duplicates. 
# Similarly, for the title '300 Miles to Heaven,' the same cast name is repeated twice.

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
39336,s1632,Movie,Rust Creek,Jen McGowan,Micah Hauptman,United States,"November 30, 2020",2018,R,108 min,Thrillers
88450,s3719,Movie,Blood Will Tell,Miguel Cohan,Oscar Martínez,Argentina,"June 21, 2019",2019,TV-MA,113 min,Dramas
88451,s3719,Movie,Blood Will Tell,Miguel Cohan,Oscar Martínez,Argentina,"June 21, 2019",2019,TV-MA,113 min,Independent Movies
88452,s3719,Movie,Blood Will Tell,Miguel Cohan,Oscar Martínez,Argentina,"June 21, 2019",2019,TV-MA,113 min,International Movies
88453,s3719,Movie,Blood Will Tell,Miguel Cohan,Oscar Martínez,United States,"June 21, 2019",2019,TV-MA,113 min,Dramas
88454,s3719,Movie,Blood Will Tell,Miguel Cohan,Oscar Martínez,United States,"June 21, 2019",2019,TV-MA,113 min,Independent Movies
88455,s3719,Movie,Blood Will Tell,Miguel Cohan,Oscar Martínez,United States,"June 21, 2019",2019,TV-MA,113 min,International Movies
88462,s3719,Movie,Blood Will Tell,Miguel Cohan,Dolores Fonzi,Argentina,"June 21, 2019",2019,TV-MA,113 min,Dramas
88463,s3719,Movie,Blood Will Tell,Miguel Cohan,Dolores Fonzi,Argentina,"June 21, 2019",2019,TV-MA,113 min,Independent Movies
88464,s3719,Movie,Blood Will Tell,Miguel Cohan,Dolores Fonzi,Argentina,"June 21, 2019",2019,TV-MA,113 min,International Movies
88465,s3719,Movie,Blood Will Tell,Miguel Cohan,Dolores Fonzi,United States,"June 21, 2019",2019,TV-MA,113 min,Dramas
88466,s3719,Movie,Blood Will Tell,Miguel Cohan,Dolores Fonzi,United States,"June 21, 2019",2019,TV-MA,113 min,Independent Movies
88467,s3719,Movie,Blood Will Tell,Miguel Cohan,Dolores Fonzi,United States,"June 21, 2019",2019,TV-MA,113 min,International Movies
88474,s3719,Movie,Blood Will Tell,Miguel Cohan,Diego Velázquez,Argentina,"June 21, 2019",2019,TV-MA,113 min,Dramas
88475,s3719,Movie,Blood Will Tell,Miguel Cohan,Diego Velázquez,Argentina,"June 21, 2019",2019,TV-MA,113 min,Independent Movies
88476,s3719,Movie,Blood Will Tell,Miguel Cohan,Diego Velázquez,Argentina,"June 21, 2019",2019,TV-MA,113 min,International Movies
88477,s3719,Movie,Blood Will Tell,Miguel Cohan,Diego Velázquez,United States,"June 21, 2019",2019,TV-MA,113 min,Dramas
88478,s3719,Movie,Blood Will Tell,Miguel Cohan,Diego Velázquez,United States,"June 21, 2019",2019,TV-MA,113 min,Independent Movies
88479,s3719,Movie,Blood Will Tell,Miguel Cohan,Diego Velázquez,United States,"June 21, 2019",2019,TV-MA,113 min,International Movies
88486,s3719,Movie,Blood Will Tell,Miguel Cohan,Paulina Garcia,Argentina,"June 21, 2019",2019,TV-MA,113 min,Dramas
88487,s3719,Movie,Blood Will Tell,Miguel Cohan,Paulina Garcia,Argentina,"June 21, 2019",2019,TV-MA,113 min,Independent Movies
88488,s3719,Movie,Blood Will Tell,Miguel Cohan,Paulina Garcia,Argentina,"June 21, 2019",2019,TV-MA,113 min,International Movies
88489,s3719,Movie,Blood Will Tell,Miguel Cohan,Paulina Garcia,United States,"June 21, 2019",2019,TV-MA,113 min,Dramas
88490,s3719,Movie,Blood Will Tell,Miguel Cohan,Paulina Garcia,United States,"June 21, 2019",2019,TV-MA,113 min,Independent Movies
88491,s3719,Movie,Blood Will Tell,Miguel Cohan,Paulina Garcia,United States,"June 21, 2019",2019,TV-MA,113 min,International Movies
88498,s3719,Movie,Blood Will Tell,Miguel Cohan,Luis Gnecco,Argentina,"June 21, 2019",2019,TV-MA,113 min,Dramas
88499,s3719,Movie,Blood Will Tell,Miguel Cohan,Luis Gnecco,Argentina,"June 21, 2019",2019,TV-MA,113 min,Independent Movies
88500,s3719,Movie,Blood Will Tell,Miguel Cohan,Luis Gnecco,Argentina,"June 21, 2019",2019,TV-MA,113 min,International Movies
88501,s3719,Movie,Blood Will Tell,Miguel Cohan,Luis Gnecco,United States,"June 21, 2019",2019,TV-MA,113 min,Dramas
88502,s3719,Movie,Blood Will Tell,Miguel Cohan,Luis Gnecco,United States,"June 21, 2019",2019,TV-MA,113 min,Independent Movies
88503,s3719,Movie,Blood Will Tell,Miguel Cohan,Luis Gnecco,United States,"June 21, 2019",2019,TV-MA,113 min,International Movies
88510,s3719,Movie,Blood Will Tell,Miguel Cohan,Malena Sánchez,Argentina,"June 21, 2019",2019,TV-MA,113 min,Dramas
88511,s3719,Movie,Blood Will Tell,Miguel Cohan,Malena Sánchez,Argentina,"June 21, 2019",2019,TV-MA,113 min,Independent Movies
88512,s3719,Movie,Blood Will Tell,Miguel Cohan,Malena Sánchez,Argentina,"June 21, 2019",2019,TV-MA,113 min,International Movies
88513,s3719,Movie,Blood Will Tell,Miguel Cohan,Malena Sánchez,United States,"June 21, 2019",2019,TV-MA,113 min,Dramas
88514,s3719,Movie,Blood Will Tell,Miguel Cohan,Malena Sánchez,United States,"June 21, 2019",2019,TV-MA,113 min,Independent Movies
88515,s3719,Movie,Blood Will Tell,Miguel Cohan,Malena Sánchez,United States,"June 21, 2019",2019,TV-MA,113 min,International Movies
88522,s3719,Movie,Blood Will Tell,Miguel Cohan,Emilio Vodanovich,Argentina,"June 21, 2019",2019,TV-MA,113 min,Dramas
88523,s3719,Movie,Blood Will Tell,Miguel Cohan,Emilio Vodanovich,Argentina,"June 21, 2019",2019,TV-MA,113 min,Independent Movies
88524,s3719,Movie,Blood Will Tell,Miguel Cohan,Emilio Vodanovich,Argentina,"June 21, 2019",2019,TV-MA,113 min,International Movies
88525,s3719,Movie,Blood Will Tell,Miguel Cohan,Emilio Vodanovich,United States,"June 21, 2019",2019,TV-MA,113 min,Dramas
88526,s3719,Movie,Blood Will Tell,Miguel Cohan,Emilio Vodanovich,United States,"June 21, 2019",2019,TV-MA,113 min,Independent Movies
88527,s3719,Movie,Blood Will Tell,Miguel Cohan,Emilio Vodanovich,United States,"June 21, 2019",2019,TV-MA,113 min,International Movies
88534,s3719,Movie,Blood Will Tell,Miguel Cohan,Norman Briski,Argentina,"June 21, 2019",2019,TV-MA,113 min,Dramas
88535,s3719,Movie,Blood Will Tell,Miguel Cohan,Norman Briski,Argentina,"June 21, 2019",2019,TV-MA,113 min,Independent Movies
88536,s3719,Movie,Blood Will Tell,Miguel Cohan,Norman Briski,Argentina,"June 21, 2019",2019,TV-MA,113 min,International Movies
88537,s3719,Movie,Blood Will Tell,Miguel Cohan,Norman Briski,United States,"June 21, 2019",2019,TV-MA,113 min,Dramas
88538,s3719,Movie,Blood Will Tell,Miguel Cohan,Norman Briski,United States,"June 21, 2019",2019,TV-MA,113 min,Independent Movies
88539,s3719,Movie,Blood Will Tell,Miguel Cohan,Norman Briski,United States,"June 21, 2019",2019,TV-MA,113 min,International Movies
135499,s6014,Movie,300 Miles to Heaven,Maciej Dejczer,Adrianna Biedrzyńska,Denmark,"October 1, 2019",1989,TV-14,93 min,Dramas
135500,s6014,Movie,300 Miles to Heaven,Maciej Dejczer,Adrianna Biedrzyńska,Denmark,"October 1, 2019",1989,TV-14,93 min,International Movies
135501,s6014,Movie,300 Miles to Heaven,Maciej Dejczer,Adrianna Biedrzyńska,France,"October 1, 2019",1989,TV-14,93 min,Dramas
135502,s6014,Movie,300 Miles to Heaven,Maciej Dejczer,Adrianna Biedrzyńska,France,"October 1, 2019",1989,TV-14,93 min,International Movies
135503,s6014,Movie,300 Miles to Heaven,Maciej Dejczer,Adrianna Biedrzyńska,Poland,"October 1, 2019",1989,TV-14,93 min,Dramas
135504,s6014,Movie,300 Miles to Heaven,Maciej Dejczer,Adrianna Biedrzyńska,Poland,"October 1, 2019",1989,TV-14,93 min,International Movies

In [1869]:
df_final.drop_duplicates(inplace=True)

In [1870]:
df_final.shape

(201826, 11)

In [1871]:
# Looping through each column in the DataFrame
# For each column, count:
#   - Real NaN values using .isnull()
#   - Text string 'nan' values using comparison (== 'nan')
# This helps to identify both actual missing data and bad string representations of missing data
for col in df_final.columns:
    real_nan = df_final[col].isnull().sum()  # Counts NaN
    string_nan = (df_final[col] == 'nan').sum()  # Counts string 'nan'
    empty_strings = (df_final[col] == '').sum()  # Counts empty strings
    print(f"Column: {col} | NaN: {real_nan} | 'nan' strings: {string_nan} | Empty strings: {empty_strings}")

Column: show_id | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: type | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: title | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: director | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: cast | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: country | NaN: 11877 | 'nan' strings: 0 | Empty strings: 32
Column: date_added | NaN: 158 | 'nan' strings: 0 | Empty strings: 0
Column: release_year | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: rating | NaN: 67 | 'nan' strings: 0 | Empty strings: 0
Column: duration | NaN: 3 | 'nan' strings: 0 | Empty strings: 0
Column: listed_in | NaN: 0 | 'nan' strings: 0 | Empty strings: 0

In [1872]:
# Checking for records with missing duration values
df_final[df_final['duration'].isnull()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
126489,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies
131555,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies
131689,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies

In [1873]:
#Create a temp column where duration is NaN
temp_df=df_final[df_final['duration'].isnull()]

In [1874]:
# Fill NaN in 'duration' with values from 'rating' column
df_final.loc[temp_df.index, 'duration'] = temp_df['rating'].values

In [1875]:
# Fill NaN in 'duration' with values from 'rating' column
# df_final['duration'] = df_final['duration'].fillna(df_final['rating'])

In [1876]:
# Replace any 'rating' values that look like durations (contain 'min') with 'NR'
df_final.loc[df_final['rating'].str.contains('min', na=False), 'rating'] = 'NR'

In [1877]:
# Display count of missing values
df_final.isnull().sum()

show_id             0
type                0
title               0
director            0
cast                0
country         11877
date_added        158
release_year        0
rating             67
duration            0
listed_in           0
dtype: int64

In [1878]:
#Fill NaN in 'rating' with 'NR'
df_final['rating'] = df_final['rating'].fillna('NR')

In [1879]:
# Display count of missing values
df_final.isnull().sum()

show_id             0
type                0
title               0
director            0
cast                0
country         11877
date_added        158
release_year        0
rating              0
duration            0
listed_in           0
dtype: int64

In [1880]:
#just an attempt to observe nulls in date_added column
df_final[df_final['date_added'].isnull()].head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
136783,s6067,TV Show,A Young Doctor's Notebook and Other Stories,Unknown Director,Daniel Radcliffe,United Kingdom,NaN,2013,TV-MA,2 Seasons,British TV Shows
136784,s6067,TV Show,A Young Doctor's Notebook and Other Stories,Unknown Director,Daniel Radcliffe,United Kingdom,NaN,2013,TV-MA,2 Seasons,TV Comedies
136785,s6067,TV Show,A Young Doctor's Notebook and Other Stories,Unknown Director,Daniel Radcliffe,United Kingdom,NaN,2013,TV-MA,2 Seasons,TV Dramas
136786,s6067,TV Show,A Young Doctor's Notebook and Other Stories,Unknown Director,Jon Hamm,United Kingdom,NaN,2013,TV-MA,2 Seasons,British TV Shows
136787,s6067,TV Show,A Young Doctor's Notebook and Other Stories,Unknown Director,Jon Hamm,United Kingdom,NaN,2013,TV-MA,2 Seasons,TV Comedies

In [1881]:
df_final[df_final['date_added'].isnull()]['release_year'].value_counts()

release_year
2015    40
2008    36
2013    27
2003    24
2012    24
2016     5
2018     1
2010     1
Name: count, dtype: int64

In [1882]:
#date added column is imputed on the basis of release year,i.e- suppose there's a null for date_added
#when release year was 2013.So below piece of code just checks the mode of date added for release year=2013
# and imputes in place of nulls the corresponding mode
for i in df_final[df_final['date_added'].isnull()]['release_year'].unique():
  imp=df_final[df_final['release_year']==i]['date_added'].mode().values[0]
  
  df_final.loc[df_final['release_year']==i,'date_added']=df_final.loc[df_final['release_year']==i,'date_added'].fillna(imp)

In [1883]:
df_final.isnull().sum()

show_id             0
type                0
title               0
director            0
cast                0
country         11877
date_added          0
release_year        0
rating              0
duration            0
listed_in           0
dtype: int64

In [1884]:
# Filling missing 'country' values by using the most common country (mode) associated with the same director,
# if the director has other entries with a known country in the dataset.
known_directors = df_final[~df_final['country'].isnull()]['director'].unique()

for director in df_final[df_final['country'].isnull()]['director'].unique():
    if director != 'Unknown Director' and director in known_directors:
        mode_country = df_final[df_final['director'] == director]['country'].mode()
        if not mode_country.empty:
            df_final.loc[(df_final['director'] == director) & (df_final['country'].isnull()), 'country'] = mode_country[0]

In [1885]:
# Extract a list of unique directors who have known (non-null) country values.
known_directors

array(['Kirsten Johnson', 'Unknown Director', 'Haile Gerima', ...,
       'Majid Al Ansari', 'Peter Hewitt', 'Mozez Singh'], dtype=object)

In [1886]:
# Check the number of missing values in each column of the final DataFrame
df_final.isnull().sum()

show_id            0
type               0
title              0
director           0
cast               0
country         9183
date_added         0
release_year       0
rating             0
duration           0
listed_in          0
dtype: int64

In [1887]:
# Imputing missing 'country' values based on the most frequent country associated with the same cast member
known_casts = df_final[~df_final['country'].isnull()]['cast'].unique()

for cast in df_final[df_final['country'].isnull()]['cast'].unique():
    if cast != 'Unknown Actor' and cast in known_casts:
        mode_cast = df_final[df_final['cast'] == cast]['country'].mode()
        if not mode_cast.empty:
            df_final.loc[(df_final['cast'] == cast) & (df_final['country'].isnull()), 'country'] = mode_cast[0]

In [1888]:
# Checking missing values only for the 'country' column
real_nan = df_final['country'].isnull().sum()  # Counts actual NaN
string_nan = (df_final['country'] == 'nan').sum()  # Counts 'nan' strings
empty_strings = (df_final['country'] == '').sum()  # Counts empty strings

print(f"Column: country | NaN: {real_nan} | 'nan' strings: {string_nan} | Empty strings: {empty_strings}")

Column: country | NaN: 5014 | 'nan' strings: 0 | Empty strings: 68

In [1889]:
df_final['country'] = df_final['country'].replace('', np.nan)  # Convert empty strings to NaN

In [1890]:
df_final['country'].isnull().sum()

5082

In [1891]:
#Filling remaining missing country values with a placeholder
df_final['country'] = df_final['country'].fillna('Unknown Country')

In [1892]:
# Looping through each column in the DataFrame
# For each column, count:
#   - Real NaN values using .isnull()
#   - Text string 'nan' values using comparison (== 'nan')
# This helps to identify both actual missing data and bad string representations of missing data
for col in df_final.columns:
    real_nan = df_final[col].isnull().sum()  # Counts NaN
    string_nan = (df_final[col] == 'nan').sum()  # Counts string 'nan'
    empty_strings = (df_final[col] == '').sum()  # Counts empty strings
    print(f"Column: {col} | NaN: {real_nan} | 'nan' strings: {string_nan} | Empty strings: {empty_strings}")

Column: show_id | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: type | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: title | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: director | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: cast | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: country | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: date_added | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: release_year | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: rating | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: duration | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: listed_in | NaN: 0 | 'nan' strings: 0 | Empty strings: 0

In [1893]:
# Count the number of occurrences of each unique value in the 'duration' column
df_final['duration'].value_counts()

# Observe that TV shows are represented by the number of seasons, 
# while movies are represented by the duration in minutes.

duration
1 Season     35015
2 Seasons     9559
3 Seasons     5084
94 min        4343
106 min       4016
             ...
3 min            4
5 min            3
11 min           2
8 min            2
9 min            2
Name: count, Length: 220, dtype: int64

In [1894]:
#Filters rows with "Season" in duration, extracts the number, and inserts it as a new column duration_seasons at index 10.
temp_df_seasons=df_final[df_final['duration'].str.contains('Season',na=False)]
temp_df_seasons.loc[:,'duration'] = temp_df_seasons['duration'].str.split().str.get(0)
duration_seasons=temp_df_seasons['duration']

df_final.insert(10,'duration_seasons',duration_seasons)

In [1895]:
#Filters rows without "Season" in duration, extracts the number, and inserts it as a new column duration_time at index 11.
temp_df_time=df_final[~df_final['duration'].str.contains('Season',na=False)]
temp_df_time.loc[:,'duration'] = temp_df_time['duration'].str.split().str.get(0)
duration_time=temp_df_time['duration']

df_final.insert(11,'duration_time',duration_time)

In [1896]:
df_final.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,duration_seasons,duration_time,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown Actor,United States,"September 25, 2021",2020,PG-13,90 min,NaN,90,Documentaries
1,s2,TV Show,Blood & Water,Unknown Director,Ama Qamata,South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,2,NaN,International TV Shows
2,s2,TV Show,Blood & Water,Unknown Director,Ama Qamata,South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,2,NaN,TV Dramas
3,s2,TV Show,Blood & Water,Unknown Director,Ama Qamata,South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,2,NaN,TV Mysteries
4,s2,TV Show,Blood & Water,Unknown Director,Khosi Ngema,South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,2,NaN,International TV Shows

In [1897]:
# Replace NaN values with 0 in specific columns
df_final['duration_seasons'] = df_final['duration_seasons'].fillna(0)
df_final['duration_time'] = df_final['duration_time'].fillna(0)

# Replace NaN values with 0 in specific columns
df_final['duration_seasons'] = df_final['duration_seasons'].astype(int)
df_final['duration_time'] = df_final['duration_time'].astype(int)

In [1898]:
# Titles like 'Boomika (Telugu)', 'Boomika (Malayalam)', 'Boomika (Hindi)' are treated as the same movie in different languages.
# The content inside brackets (e.g., the language) is removed to ensure consistency in the title.
# This operation also trims any leading or trailing spaces from the title.
df_final['title'] = df_final['title'].str.replace(r"\s*\(.*\)\s*", "", regex=True).str.strip()

In [1899]:
# with pd.option_context('display.max_rows', None):
#     print(df_final['title'].value_counts().sort_index())
print(df_final['title'].value_counts())

title
Kahlil Gibran's The Prophet       700
Holidays                          504
Movie 43                          468
The Eddy                          416
Narcos                            378
                                 ...
Droppin' Cash: Los Angeles          1
Jeff Dunham: Relative Disaster      1
Heroin                              1
Russell Peters: Notorious           1
Dick Johnson Is Dead                1
Name: count, Length: 8776, dtype: int64

In [1900]:
df_final.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'duration_seasons',
       'duration_time', 'listed_in'],
      dtype='object')

In [1901]:
# This code processes the 'date_added' column in the DataFrame by:

from dateutil.parser import parse
# Step 1:Converting it to a string and stripping any extra spaces.
df_final['date_added'] = df_final['date_added'].astype(str).str.strip()  # Convert to string and strip

# Step 2: Convert to datetime safely (in case of any invalid date format)
df_final['date_added'] = pd.to_datetime(df_final['date_added'], errors='coerce')

# Step 3: Extracting the month, week, and year from the 'date_added' column
month_added = df_final['date_added'].dt.month
week_added = df_final['date_added'].dt.isocalendar().week
year_added= df_final['date_added'].dt.year

#Step 4. Inserting the extracted values as new columns: 'month_added', 'week_added', and 'year_added'.
df_final.insert(7,'month_added',month_added)
df_final.insert(8,'week_added',week_added)
df_final.insert(9,'year_added',year_added)

In [1902]:
df_final.head()

,show_id,type,title,director,cast,country,date_added,month_added,week_added,year_added,release_year,rating,duration,duration_seasons,duration_time,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown Actor,United States,2021-09-25,9,38,2021,2020,PG-13,90 min,0,90,Documentaries
1,s2,TV Show,Blood & Water,Unknown Director,Ama Qamata,South Africa,2021-09-24,9,38,2021,2021,TV-MA,2 Seasons,2,0,International TV Shows
2,s2,TV Show,Blood & Water,Unknown Director,Ama Qamata,South Africa,2021-09-24,9,38,2021,2021,TV-MA,2 Seasons,2,0,TV Dramas
3,s2,TV Show,Blood & Water,Unknown Director,Ama Qamata,South Africa,2021-09-24,9,38,2021,2021,TV-MA,2 Seasons,2,0,TV Mysteries
4,s2,TV Show,Blood & Water,Unknown Director,Khosi Ngema,South Africa,2021-09-24,9,38,2021,2021,TV-MA,2 Seasons,2,0,International TV Shows

In [1903]:
# Let's do a final check on the cleaned data.
df_final_info = {
    "Shape": df_final.shape,
    "Missing Values": df_final.isnull().sum(),
    "Data Types": df_final.dtypes,
    "First Few Rows": df_final.head()
}

df_final_info

{'Shape': (201826, 16),
 'Missing Values': show_id             0
 type                0
 title               0
 director            0
 cast                0
 country             0
 date_added          0
 month_added         0
 week_added          0
 year_added          0
 release_year        0
 rating              0
 duration            0
 duration_seasons    0
 duration_time       0
 listed_in           0
 dtype: int64,
 'Data Types': show_id                     object
 type                        object
 title                       object
 director                    object
 cast                        object
 country                     object
 date_added          datetime64[ns]
 month_added                  int32
 week_added                  UInt32
 year_added                   int32
 release_year                 int64
 rating                      object
 duration                    object
 duration_seasons             int32
 duration_time                int32
 listed_in                   object
 dtype: object,
 'First Few Rows':   show_id     type                 title          director           cast  \
 0      s1    Movie  Dick Johnson Is Dead   Kirsten Johnson  Unknown Actor
 1      s2  TV Show         Blood & Water  Unknown Director     Ama Qamata
 2      s2  TV Show         Blood & Water  Unknown Director     Ama Qamata
 3      s2  TV Show         Blood & Water  Unknown Director     Ama Qamata
 4      s2  TV Show         Blood & Water  Unknown Director    Khosi Ngema

          country date_added  month_added  week_added  year_added  \
 0  United States 2021-09-25            9          38        2021
 1   South Africa 2021-09-24            9          38        2021
 2   South Africa 2021-09-24            9          38        2021
 3   South Africa 2021-09-24            9          38        2021
 4   South Africa 2021-09-24            9          38        2021

    release_year rating   duration  duration_seasons  duration_time  \
 0          2020  PG-13     90 min                 0             90
 1          2021  TV-MA  2 Seasons                 2              0
 2          2021  TV-MA  2 Seasons                 2              0
 3          2021  TV-MA  2 Seasons                 2              0
 4          2021  TV-MA  2 Seasons                 2              0

                 listed_in
 0           Documentaries
 1  International TV Shows
 2               TV Dramas
 3            TV Mysteries
 4  International TV Shows  }

In [1904]:
#This code is dropping the "duration" column from the df_final DataFrame and assigning the result to a new DataFrame export_df
export_df = df_final.drop(columns=['duration'])

In [1905]:
export_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 201826 entries, 0 to 201880
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   show_id           201826 non-null  object
 1   type              201826 non-null  object
 2   title             201826 non-null  object
 3   director          201826 non-null  object
 4   cast              201826 non-null  object
 5   country           201826 non-null  object
 6   date_added        201826 non-null  datetime64[ns]
 7   month_added       201826 non-null  int32
 8   week_added        201826 non-null  UInt32
 9   year_added        201826 non-null  int32
 10  release_year      201826 non-null  int64
 11  rating            201826 non-null  object
 12  duration_seasons  201826 non-null  int32
 13  duration_time     201826 non-null  int32
 14  listed_in         201826 non-null  object
dtypes: UInt32(1), datetime64[ns](1), int32(4), int64(1), object(8)
memory usage: 25.0+ MB

In [1906]:
# Final data quality check before exporting the cleaned dataset
for col in export_df.columns:
    real_nan = export_df[col].isnull().sum()  # Counts NaN
    string_nan = (export_df[col] == 'nan').sum()  # Counts string 'nan'
    empty_strings = (export_df[col] == '').sum()  # Counts empty strings
    print(f"Column: {col} | NaN: {real_nan} | 'nan' strings: {string_nan} | Empty strings: {empty_strings}")

Column: show_id | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: type | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: title | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: director | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: cast | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: country | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: date_added | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: month_added | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: week_added | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: year_added | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: release_year | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: rating | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: duration_seasons | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: duration_time | NaN: 0 | 'nan' strings: 0 | Empty strings: 0
Column: listed_in | NaN: 0 | 'nan' strings: 0 | Empty strings: 0

In [1997]:
export_df.to_csv('Netflix_cleaned_dataset.csv', index=False)

In [2007]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Netflix_Datacleaning.ipynb
	deleted:    Netflix_cleaned_data.csv

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/EDA on Netflix-checkpoint.ipynb
	.ipynb_checkpoints/Netflix_Datacleaning-checkpoint.ipynb
	.ipynb_checkpoints/Netflix_cleaned_data-checkpoint.csv
	EDA on Netflix.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [2001]:
!git add Netflix_Datacleaning.ipynb Netflix_cleaned_dataset.csv

warning: in the working copy of 'Netflix_Datacleaning.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Netflix_cleaned_dataset.csv', LF will be replaced by CRLF the next time Git touches it

In [2003]:
!git commit -m "Final data cleaning and exported cleaned dataset"

[main f820783] Final data cleaning and exported cleaned dataset
 2 files changed, 201969 insertions(+), 138 deletions(-)
 create mode 100644 Netflix_cleaned_dataset.csv

In [2005]:
!git push

To https://github.com/PatraRupali/EDAOnNetflix.git
   617e2cc..f820783  main -> main